---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен работать стабильно без частых сбоев или отказов.
  - Сайт должен предоставлять различные безопасные способы оплаты (платежные карты, электронные кошельки, банковский перевод).
  - Пользователи могут прочитать отзывы о товарах и посмотреть рейтинги других покупателей, чтобы принимать более обоснованные решения.
  - На странице оформления заказа должна быть четко указана информация о стоимости и сроках доставки.
  - Магазин должен иметь простую и понятную политику возврата и обмена товаров.
  - Пользователи ожидают получать уведомления на почту или телефон о статусе их заказа — подтверждение, отправка, доставка и т.д.
  - Пользователи могут ожидать, что служба поддержки будет доступна не только в рабочее время, но и в вечерние часы или по выходным.
  - Информация о товарах, доставке и оплате должна быть актуальной и регулярно обновляться.
  - Наличие системы рекомендаций для увеличения продаж и улучшения опыта покупок.
