---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен работать стабильно без частых сбоев или отказов.
  - Сайт должен мгновенно реагировать на действия пользователя, например, на клики по кнопкам, ввод текста в поисковую строку и т.д.
  - Сайт должен предоставлять различные безопасные способы оплаты (платежные карты, электронные кошельки, банковский перевод).
  - Информация о товарах, доставке и оплате должна быть актуальной и регулярно обновляться.
  - На странице оформления заказа должна быть четко указана информация о стоимости и сроках доставки.
  - Магазин должен иметь простую и понятную политику возврата и обмена товаров.
  - Пользователи ожидают получать уведомления на почту или телефон о статусе их заказа — подтверждение, отправка, доставка и т.д.
  - Пользователю должна быть доступна контактная информация для связи со службой поддержки через различные каналы, такие как чат, телефон и электронная почта.
  - Пользователи могут ожидать, что служба поддержки будет доступна не только в рабочее время, но и в вечерние часы или по выходным.
  - На странице товара и в каталоге должно отображаться название товара.
  - На странице товара и в каталоге должнен отображать рейтинг товара.
  - Пользователь должен мочь вытсавлять рейтинг товара, а также смотреть рейтинги других покупателей.
  - На странице товара и в каталоге должна быть цена со скидкой и без нее и регулярно обновляться.
  - Пользователь должен легко находить нужные товары, категории, информацию о доставке и оплате. 
  - Дизайн сайта должен быть современным и визуально привлекательным, отражая актуальные тенденции в веб-дизайне.
  - Описание товаров в русскоязычной версии интернет-магазина должно предоставляться на русском языке.
  - В русскоязычной версии интернет-магазина цена товара должна отображаться в рублях.
